### PR TITLE
V 6

### PR DESCRIPTION
**Pull request by tillsc**
Support MultiMarkdown-6

### CODE REVIEW

**Comment by tillsc** [comment]
Travis is green... lets go

**Comment by tillsc** [comment]
Im such an idiot

**Comment by jesperronn** [comment]
This is great news! Thanks for your effort! 🎉

**Comment by jesperronn** [comment]
Also, I suspect this corresponds to the new, shiny release: https://github.com/tillsc/multi_markdown/releases/tag/6.2.2.1

**Comment by tillsc** [comment]
It is pushed to rubygems already: https://rubygems.org/gems/rmultimarkdown/versions/6.2.2.1

**Pull request merged**
